package edu.byu.cs.tweeter.model.service;

import java.io.IOException;

import edu.byu.cs.tweeter.model.service.request.SignUpRequest;
import edu.byu.cs.tweeter.model.service.response.SignUpResponse;

/**
 * Defines the interface for the 'sign up' service.
 */
public interface SignUpService {
    /**
     * Returns the new user object generated by the database using the specified information in the request.
     *
     * @param request contains the data required to fulfill the request.
     * @return the user.
     */
    SignUpResponse postSignUp(SignUpRequest request) throws IOException;
}
